{{- define "containers-init-linux" -}}
- name: init-volume
  image: "{{ include "image-path" (dict "root" .Values "image" .Values.agents.image) }}"
  imagePullPolicy: {{ .Values.agents.image.pullPolicy }}
  {{- if eq (include "agent-has-single-entrypoint" .) "false" }}
  command: ["bash", "-c"]
  args:
    - cp -r /etc/datadog-agent /opt
  {{- end }}
  {{- if eq (include "agent-has-single-entrypoint" .) "true" }}
  env:
    - name: ENTRYPOINT
      value: init-volume
  {{- end }}
  volumeMounts:
    - name: config
      mountPath: /opt/datadog-agent
  resources:
{{ toYaml .Values.agents.containers.initContainers.resources | indent 4 }}
- name: init-config
  image: "{{ include "image-path" (dict "root" .Values "image" .Values.agents.image) }}"
  imagePullPolicy: {{ .Values.agents.image.pullPolicy }}
  {{- if eq (include "agent-has-single-entrypoint" .) "false" }}
  command: ["bash", "-c"]
  args:
    - for script in $(find /etc/cont-init.d/ -type f -name '*.sh' | sort) ; do bash $script ; done
  {{- end }}
  volumeMounts:
    - name: logdatadog
      mountPath: /var/log/datadog
    - name: config
      mountPath: /etc/datadog-agent
    {{- if (or (.Values.datadog.confd) (.Values.datadog.autoconf)) }}
    - name: confd
      mountPath: /conf.d
      readOnly: true
    {{- end }}
    {{- if .Values.datadog.checksd }}
    - name: checksd
      mountPath: /checks.d
      readOnly: true
    {{- end }}
    - name: procdir
      mountPath: /host/proc
      mountPropagation: {{ .Values.datadog.hostVolumeMountPropagation }}
      readOnly: true
    - name: runtimesocketdir
      mountPath: {{ print "/host/" (dir (include "datadog.dockerOrCriSocketPath" .)) | clean }}
      mountPropagation: {{ .Values.datadog.hostVolumeMountPropagation }}
      readOnly: true
    {{- if eq (include "should-enable-system-probe" .) "true" }}
    - name: sysprobe-config
      mountPath: /etc/datadog-agent/system-probe.yaml
      subPath: system-probe.yaml
    {{- end }}
  env:
    {{- if eq (include "agent-has-single-entrypoint" .) "true" }}
    - name: ENTRYPOINT
      value: init-config
    {{- end }}
    {{- include "containers-common-env" . | nindent 4 }}
    {{- if and (eq (include "cluster-agent-enabled" .) "false") .Values.datadog.leaderElection }}
    - name: DD_LEADER_ELECTION
      value: {{ .Values.datadog.leaderElection | quote }}
    {{- end }}
  resources:
{{ toYaml .Values.agents.containers.initContainers.resources | indent 4 }}
{{- end -}}
