# Datadog Agent on GKE cluster

targetSystem: "linux"
## On GKE Autopilot, registry needs to be GCR
registry: gcr.io/datadoghq
datadog:
  apiKeyExistingSecret: <DATADOG_API_KEY_SECRET>
  appKeyExistingSecret: <DATADOG_APP_KEY_SECRET>
  clusterName: <CLUSTER_NAME>
  tags: []
  ## On GKE Standard cluster, no specific configuration is required
  logs:
    enabled: true
    containerCollectAll: false
    containerCollectUsingFiles: true
  apm:
    portEnabled: true
    socketPath: /var/run/datadog/apm.socket
    hostSocketPath: /var/run/datadog/
  processAgent:
    enabled: true
    processCollection: false
  systemProbe:
    enableTCPQueueLength: false
    enableOOMKill: true
    collectDNSStats: false
## Recommended to set resource limits on GKE Autopilot
## See: https://docs.datadoghq.com/containers/kubernetes/distributions/?tab=helm#autopilot
# agents:
#   containers:
#     agent:
#       resources:
#         requests:
#           cpu: 200m
#           memory: 256Mi
#         limits:
#           cpu: 200m
#           memory: 256Mi
#     traceAgent:
#       resources:
#         requests:
#           cpu: 100m
#           memory: 200Mi
#         limits:
#           cpu: 100m
#           memory: 200Mi
#     processAgent:
#       resources:
#         requests:
#           cpu: 100m
#           memory: 200Mi
#         limits:
#           cpu: 100m
#           memory: 200Mi
# Required to set `true` on GKE Autopilot
# providers:
  # gke:
    # autopilot: true          